### ISSUE TITLE
where to download the tar or img file?

### ISSUE THREAD

**Issue by tim-hub** [jcadduono/android_device_samsung_zerofltezt#1]
- https://twrp.me/devices/samsunggalaxys6.html
- https://dl.twrp.me/zerofltezt  this link give me a 404

can I use this https://dl.twrp.me/zeroflte instead?

Thanks in advance

**Comment by jcadduono** [comment]
The link works fine for me, try it again?

**Comment by tim-hub** [comment]
yeah, got it.

can you build a tar file too?

or could you tell me how to build a tar file? just compress the img to a tar?

**Comment by jcadduono** [comment]
actually dont download it, its from an older build i think, bigbiff hasnt started building new versions yet from my sources
you will want to grab from here for now.. 
https://idlekernel.com/twrp/zeroflte/

**Comment by tim-hub** [comment]
@jcadduono thanks, Another issue happened. when I use odin to install the recovery, now I cannot get into recoverymode with home volume+ and battery button

**Comment by tim-hub** [comment]
and now, my phone became a brick, with samsung galaxy s6 logo looping.

and after I re use odin to install stock rom, the looping is gone.

**Comment by jcadduono** [comment]
You have to flash DM verity removal zip after swiping to enable modifications in twrp otherwise you can't boot in marshmallow

**Comment by tim-hub** [comment]
where is the zip file, in twrp?
